/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubRouteImport } from './routes/_sub'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as SubTodoIndexRouteImport } from './routes/_sub/todo/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as SubAuthRegisterRouteImport } from './routes/_sub/auth/register'
import { Route as SubAuthLoginRouteImport } from './routes/_sub/auth/login'

const SubRoute = SubRouteImport.update({
  id: '/_sub',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const SubTodoIndexRoute = SubTodoIndexRouteImport.update({
  id: '/todo/',
  path: '/todo/',
  getParentRoute: () => SubRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SubAuthRegisterRoute = SubAuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => SubRoute,
} as any)
const SubAuthLoginRoute = SubAuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => SubRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/auth/login': typeof SubAuthLoginRoute
  '/auth/register': typeof SubAuthRegisterRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/todo/': typeof SubTodoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof LayoutIndexRoute
  '/auth/login': typeof SubAuthLoginRoute
  '/auth/register': typeof SubAuthRegisterRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/todo': typeof SubTodoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_sub': typeof SubRouteWithChildren
  '/_layout/': typeof LayoutIndexRoute
  '/_sub/auth/login': typeof SubAuthLoginRoute
  '/_sub/auth/register': typeof SubAuthRegisterRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_sub/todo/': typeof SubTodoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth/login' | '/auth/register' | '/api/auth/$' | '/todo/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth/login' | '/auth/register' | '/api/auth/$' | '/todo'
  id:
    | '__root__'
    | '/_layout'
    | '/_sub'
    | '/_layout/'
    | '/_sub/auth/login'
    | '/_sub/auth/register'
    | '/api/auth/$'
    | '/_sub/todo/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  SubRoute: typeof SubRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_sub': {
      id: '/_sub'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_sub/todo/': {
      id: '/_sub/todo/'
      path: '/todo'
      fullPath: '/todo/'
      preLoaderRoute: typeof SubTodoIndexRouteImport
      parentRoute: typeof SubRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_sub/auth/register': {
      id: '/_sub/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof SubAuthRegisterRouteImport
      parentRoute: typeof SubRoute
    }
    '/_sub/auth/login': {
      id: '/_sub/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof SubAuthLoginRouteImport
      parentRoute: typeof SubRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

interface SubRouteChildren {
  SubAuthLoginRoute: typeof SubAuthLoginRoute
  SubAuthRegisterRoute: typeof SubAuthRegisterRoute
  SubTodoIndexRoute: typeof SubTodoIndexRoute
}

const SubRouteChildren: SubRouteChildren = {
  SubAuthLoginRoute: SubAuthLoginRoute,
  SubAuthRegisterRoute: SubAuthRegisterRoute,
  SubTodoIndexRoute: SubTodoIndexRoute,
}

const SubRouteWithChildren = SubRoute._addFileChildren(SubRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  SubRoute: SubRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
